# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Amirmahdi Sadeghzadeh
tagline:             ''
description:         '![Lanyon](https://avatars1.githubusercontent.com/u/16166638?s=400&u=d70685862c52745999114109ea75052ac5f31150&v=4)
 Ph.D. Candidate at <a href="http://www.en.sharif.edu/" target="_blank">Sharif University and Technology</a>'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Amirmahdi Sadeghzadeh
  url:               amsadeghzadeh.github.io
  email:             amsadeghzadeh@gmail.com

# Custom vars
version:             1.0.0
