# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Amirmahdi Sadeghzadeh
tagline:             ''
description:         'Ph.D. Candidate at Sharif University and Technology'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Amirmahdi Sadeghzadeh
  url:               amsadeghzadeh.github.io
  email:             amsadeghzadeh@gmail.com

# Custom vars
version:             1.0.0
