# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Amir Mahdi Sadeghzadeh
tagline:             ''
description:         'Amir Mahdi Sadeghzadeh<br>Ph.D. Candidate at Sharif University of Technology<br>Email:<br>amsadeghzadeh_at_ce.sharif.edu'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Amir Mahdi Sadeghzadeh
  url:               amsadeghzadeh.github.io
  email:             amsadeghzadeh@gmail.com

# Custom vars
version:             1.0.0
